name: Deploy DocC

on:
  push:
    branches: [ "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: xcode-27
    steps:
      - uses: actions/checkout@v7
      - name: build docc
        run: |
          swift package --allow-writing-to-directory ./docs generate-documentation \
          --target SwiftAutoGUI \
          --target SwiftAutoGUIBrowser \
          --enable-experimental-combined-documentation \
          --transform-for-static-hosting \
          --hosting-base-path SwiftAutoGUI \
          --output-path ./docs
      - uses: actions/upload-pages-artifact@v5
        with:
          path: docs

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v5
